<a href="https://colab.research.google.com/github/metsumesquita/Python_resumo/blob/main/vetor%2Ctuplas_e_matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#estrutura de dados em python

#Vetores
[*array*](https://numpy.org/doc/stable/user/basics.creation.html)

[index](https://thispointer.com/find-the-index-of-a-value-in-numpy-array/)


O NumPy fornece um tipo de matriz N-dimensional, o ndarray, que descreve uma coleção de “itens” do mesmo tipo. Os itens podem ser indexados usando, por exemplo, N inteiros.

Todos os ndarrays são homogêneos: cada item ocupa um bloco de memória do mesmo tamanho e todos os blocos são interpretados exatamente da mesma maneira. A forma como cada item da matriz deve ser interpretado é especificada por um objeto de tipo de dados separado, um dos quais está associado a cada matriz. Além dos tipos básicos (inteiros, flutuantes, etc.), os objetos de tipo de dados também podem representar estruturas de dados.

Um item extraído de uma matriz, por exemplo, por indexação, é representado por um objeto Python cujo tipo é um dos tipos escalares de matriz incorporados no NumPy. Os escalares de matriz permitem a fácil manipulação de arranjos de dados mais complexos.
Em Python, vetores são tipicamente implementados usando a biblioteca NumPy (numpy.array), enquanto séries são a estrutura de dados unidimensional fundamental da biblioteca Pandas (pandas.Series).
 Ambas são usadas para manipulação eficiente de dados, mas com diferenças importantes.
Vetores (NumPy Arrays)
Vetores em Python são comumente referidos como arrays NumPy. Eles são eficientes para operações matemáticas e numéricas.
Homogeneidade: Todos os elementos em um array NumPy devem ser do mesmo tipo de dado (ex: todos inteiros ou todos floats).
Performance: São otimizados para operações de alto desempenho, especialmente em cálculos científicos e machine learning.
Funcionalidade: Focam em operações matemáticas otimizadas (funções universais ou ufuncs

In [ ]:
import numpy as np

a = np.array([2, 3, 4, 5, 6,10,15, 45, 67, 34])

In [ ]:
a[:]

array([ 2,  3,  4,  5,  6, 10, 15, 45, 67, 34])

In [ ]:
#criar uma cópia rápida e invertida
a[::-1]

array([34, 67, 45, 15, 10,  6,  5,  4,  3,  2])

In [ ]:
vetor_invertido = np.flip(a)
print(vetor_invertido)

[34 67 45 15 10  6  5  4  3  2]

In [ ]:
import numpy as np
vetor=np.array([2,4,5,6])
tamanho_real=len(vetor)-1
contador= tamanho_real
vetor_invertido=[]

while contador>=0:
  vetor_invertido.append(vetor[contador])
  contador=contador-1

print(vetor_invertido)

[np.int64(6), np.int64(5), np.int64(4), np.int64(2)]

In [ ]:
a.size

11

In [ ]:
vetor = [2, 4, 5, 6]
vetor_invertido = vetor[::-1]

In [ ]:
len(a)

11

In [ ]:
result = np.where(a == 15)
print('retorno do array e posiçao : ', result)
print("retornando a possiçao onde o elemento de valor 15 é encontrato ", result[0], sep='\n')

In [ ]:
#cria um vetor que cresce regularmente /
np.arange(10)

In [ ]:
#numpy.linspace criará arrays com um número especificado de elementos
#e espaçado igualmente entre os valores inicial e final especificados.
np.linspace(0., 8., 6)

In [ ]:
#array de duas dimensoes
a2D = np.array([[1, 2], [3, 4]])

In [ ]:
#esse exemplo é uma matriz identidade
#onde quando i=j sera igual a 1(linha coluna)
np.eye(4, 4)

In [ ]:

import numpy as np

# create numpy array elements
a = np.array([2, 3, 4, 5, 6, 45, 67, 34])

# display element index where value = 45

index_of_element = -1
for i in range(a.size):
    if a[i] == 45:
        index_of_element = i
        break

if index_of_element != -1:
    print("element index  : ", index_of_element)
else:
    print("The element not present")

In [ ]:
#podemos tranforma uma lista em um array
list_number=[3,5,4,2,1,5,6,7,3]

#aqui é feito um cast
array_1d=np.array(list_number)
type(arr)

In [ ]:
def valores_faltantes(nums):
    nums = sorted(set(nums))  # remove duplicatas e ordena
    faltando = []
    for i in range(nums[0], nums[-1]):
        if i not in nums:
            faltando.append(i)
    return faltando
lista = [10, 11, 13, 14, 16, 20]
print(valores_faltantes(lista))

[12, 15, 17, 18, 19]

Series são arrays unidimensionais capazes de armazenar qualquer tipo de dado - basicamente vetores, mas não se preocupe com os termos, caso seja novidade para você. Cada elemento das Series tem um índice associado. Elas podem ser usada para representar séries temporais, sequências de valores, ou listas de elementos unidimensionais. A criação delas é feita a partir de listas, dicionários, ou arrays do NumPy.

In [ ]:
import pandas as pd
s=pd.Series([1,2,3,4,5])
print(s)

#Tuples ou tuplas


---
######Imutáveis: Uma vez criadas, as tuplas não podem ser alteradas. Isso significa que você não pode adicionar, remover ou modificar elementos dentro de uma tupla.
######Tipos de Dados: Podem armazenar diferentes tipos de dados na mesma coleção (por exemplo, uma tupla pode conter um número, uma string e uma lista).
#####Métodos: As tuplas têm menos métodos disponíveis em comparação com listas. Por exemplo, não têm métodos como append ou remove porque não podem ser modificadas.
#####Troca de Valores: Um exemplo clássico de uso de tuplas é a troca de valores entre variáveis. Isso é feito de maneira elegante e simples com tuplas, assim: a, b = b, a.

In [ ]:
a = [1, 4, 3]
b = [3, 2, 2]

def store_original_ids():
    a = [1, 4, 3]
    b = [3, 2, 2]

store_original_ids()
#aqui tempos um SWAP
temp =b
b=a
a=temp
#que tambem poderia ser resolvido assim

##a, b = a, b

def check():
     if a==[3, 2, 2] and b ==[1, 4, 3] :
            print('certo')

check()

In [ ]:
#"Dada a tupla de salários dos funcionários de uma área:
salarios = [2500, 3000, 2800, 3100, 2900]
#converter
lista_salario=list(salarios)
#adicionar
lista_salario.append(3200)
#organizar
lista_salario.sort()
#converter
tupla_ordenada=tuple(lista_salario)

In [ ]:
Estados = namedtuple('Estados', ['sigla', 'nome'])
estado_pe = Estados('PE', 'Recife')
estado_pe

In [ ]:
Estados(sigla='PE', nome='recife')
print(estado_pe.sigla)
print(estado_pe.nome)

In [ ]:
#devemos  usar uma 3 variavel para fazer o wap funcionar corretamente
#caso contrario um dos valores das variaveis sera perdido
#observe abaixo:
coordenada_xy = (10, 20)
x, y = coordenada_xy
temp=x   # 10
x=y      # 20
y=temp   # 10
#portanto usamos a variavel temp para armazena o valor de x antes dele ser modificado/substituido por um novo valor
print("valor de variavel  x : "+str(x)+   "\n"
     +"valor de variavel  y : "+ str(y) + "\n"
    + "valor de variavel temp : "+ str(temp))
#para usar esses valores que conhecemos precisamos colocar eles como se fossem string

In [ ]:
# Swap com tuplas.
print("x e y antes do swap: ", x, y)

x, y = y, x

print("x e y depois do swap: ", x, y)

In [ ]:
tupla_nomes = ('Giordano', 'Paulo', 'Lucas', 'João', 'Felipe')
#se o elemento esta na tupla
print('Giordano' in tupla_nomes)

print('Paulo' in tupla_nomes)

print (tupla_nomes.count('Lucas')) #< possui unica vez o nome lucas

print(tupla_nomes.index("João"))# retorna a posiçao na tupla

In [ ]:
# tupla com apenas um elemento
#nao precisa usar sempre ()
tupla_elemento = 10,
tupla_elemento

In [ ]:
nick=("n","i","n","a")

nick.index("n")#retorna a vez q aparece primeiro

In [ ]:
name_1=("m","a","r","i","a","n","a")

print(name_1.index("n"))#retorna a vez q aparece primeiro

print(name_1.index("a"))

#matrizes

In [ ]:
import numpy as np

# uma matriz de 3 d
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])
print(matrix)

[[1 2]
 [1 2]
 [1 2]]

In [ ]:
import numpy as np
#aqui uma matrix de 3d
matrix=[[11,12,13],[21,22,23],[31,32,33]]
array_3D=np.array(matrix)
print(array_3D)

[[11 12 13]
 [21 22 23]
 [31 32 33]]

In [ ]:
"""uma operação X numa matriz circular desloca cada um dos elementos da matriz uma unidade para a esquerda.
Os elementos que saem pela extremidade esquerda reaparecem na extremidade direita.
Dado um número inteiro chamado de d, rode a matriz esse número de passos para a esquerda e devolva o resultado.

int d é a quantiade de vezes que ira ser rotacionado
int arr[n] é o array a ser rotacionado
de tal  forma que se n =5 e d=4
array= [1,2,3,4,5]
na primeira rotação
[1,2,3,4,5]->[2,3,4,5,1]
na segunda rotaçao
[2,3,4,5,1]->[3,4,5,1,2]
na terceira rotaçao
[3,4,5,1,2]->[4,5,1,2,3]
na quarta rotaçao
[4,5,1,2,3]->[5,1,2,3,4]
resultado final
[5,1,2,3,4]
"""

In [ ]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

In [ ]:
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(a3D[0])

[[1 2]
 [3 4]]

In [ ]:
print(a3D[1])

[[5 6]
 [7 8]]

In [ ]:
#retorma o numero de dimensoes de um array
print(a3D.ndim)

3

##DATAFRAME
[texto do link](https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf)


Um DataFrame é uma estrutura de dados com duas dimensões (linhas x colunas), mutável e que é fundamental para nossas análises de dados, pois funciona de forma semelhante a uma planilha de Excel. Mais uma vez, deixando a formalidade de lado, o DataFrame é como uma tabela,sendo que cada coluna vai ser uma variável e cada linha uma observação. Se você tivesse uma tabela com as informações de compras dos clientes, as linhas teriam as compras feitas e as colunas teriam as informações de cada compra (data, valor, etc). Isso seria um DataFrame no Pandas.
A DataFrame is a 2-dimensional data structure that can store data of different types (including characters, integers, floating point values, categorical data and more) in columns. It is similar to a spreadsheet, a SQL table or the data.frame in R.

In [ ]:
import pandas as pd
data={
    "name":['namir','gabi','lucas','pedro','floriana','kaius','bernado','fernanda','linus'],
    "age":[21,23,30,12,2,27,40,21,30],
    "gender":['fem','fem','male','male','fem','male','male','female','male']
}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    9 non-null      object
 1   age     9 non-null      int64
 2   gender  9 non-null      object
dtypes: int64(1), object(2)
memory usage: 348.0+ bytes

In [ ]:
df.head()

       name  age gender
0     namir   21    fem
1      gabi   23    fem
2     lucas   30   male
3     pedro   12   male
4  floriana    2    fem

In [ ]:
#linha 1 coluna 2
#coluna 2 = gender
#a linha 1 é a gabi
df.iloc[1,2]

'fem'

In [ ]:
df.columns

Index(['name', 'age', 'gender'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=9, step=1)

In [ ]:
df.describe()

             age
count   9.000000
mean   22.888889
std    11.027743
min     2.000000
25%    21.000000
50%    23.000000
75%    30.000000
max    40.000000

In [ ]:
df.loc[2]

name      lucas
age          30
gender     male
Name: 2, dtype: object

#Creating a DataFrame by passing a NumPy array with a datetime index using date_range() and labeled columns:

In [ ]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

In [ ]:
df["A"]